export const leftPosition: string;
export const rightPosition: string;
export const borderRight: string;
export const vContent: string;
export const logo: string;
export const phone: string;
export const phoneHeader: string;
export const phoneContent: string;
export const phoneFooter: string;
